### ISSUE TITLE
Beta plots for low pressure range:

### ISSUE THREAD

**Issue by cparts1** [andyletzhang/SwatGrains#11]
Narrow fits and plot beta against lambda, alpha, and pin #

**Comment by andyletzhang** [comment]
Trying a few different cutoffs for low pressure; some of our data sets start breaking at lower pressure/r_s^2 values, but most of them still look okay at a point where we begin to see some interesting behavior. Unexpectedly, for low pressures, high pin numbers &beta; starts pulling down again for square and random lattices:
![beta_vs_alpha-lowest_pressure](https://user-images.githubusercontent.com/73668875/100949019-7d94ba00-34c6-11eb-9bfe-e285207eb746.jpg)

This investigation will also be more comprehensive when we get lower pressure data.
